captainVersion: 4
services:
    $$cap_appname-db:
        caproverExtra:
            notExposeAsWebApp: 'true'
        image: postgres:$$cap_POSTGRES_VERSION
        restart: always
        environment:
            POSTGRES_DB: $$cap_DATABASE_NAME
            POSTGRES_USER: $$cap_DATABASE_USER
            POSTGRES_PASSWORD: $$cap_DATABASE_PASS
        volumes:
            - $$cap_appname-db:/var/lib/postgresql/data
    $$cap_appname-grafana:
        caproverExtra:
            containerHttpPort: 3000
            websocketSupport: 'true'
        image: teslamate/grafana:latest
        restart: always
        environment:
            DATABASE_USER: $$cap_DATABASE_USER
            DATABASE_PASS: $$cap_DATABASE_PASS
            DATABASE_NAME: $$cap_DATABASE_NAME
            DATABASE_HOST: srv-captain--$$cap_appname-db
        volumes:
            - $$cap_appname-db:/var/lib/postgresql/data
        depends_on:
            - $$cap_appname-db
    $$cap_appname-mqtt:
        caproverExtra:
            notExposeAsWebApp: 'true'
        image: eclipse-mosquitto:2
        restart: always
        command: mosquitto -c /mosquitto-no-auth.conf
        volumes:
            - $$cap_appname-mosquitto-conf:/mosquitto/config
            - $$cap_appname-mosquitto-data:/mosquitto/data
    $$cap_appname:
        caproverExtra:
            containerHttpPort: 4000
            websocketSupport: 'true'
        image: teslamate/teslamate:latest
        environment:
            ENCRYPTION_KEY: $$cap_SECRET_KEY
            DATABASE_USER: $$cap_DATABASE_USER
            DATABASE_PASS: $$cap_DATABASE_PASS
            DATABASE_NAME: $$cap_DATABASE_NAME
            DATABASE_HOST: srv-captain--$$cap_appname-db
            MQTT_HOST: srv-captain--$$cap_appname-mqtt
        volumes:
            - $$cap_appname-import:/opt/app/import
        depends_on:
            - $$cap_appname-db
caproverOneClickApp:
    displayName: TeslaMate
    description: A powerful, self-hosted data logger for your Tesla.
    isOfficial: true
    instructions:
        start: |-
            TeslaMate is a powerful self-hosted data logger for your Tesla.
        end: |-
            TeslaMate has been successfully deployed! It might take few moments before it's fully started.
            You can access it at `http://$$cap_appname.$$cap_root_domain` and set up your account.
            Read more at `https://docs.teslamate.org/docs/installation/docker#usage` for further instructions and usage.
            **Important:** Please enable **HTTPS** and **WebSocket Support**.
    variables:
        - id: $$cap_SECRET_KEY
          label: Application | Encryption
          defaultValue: $$cap_gen_random_hex(8)
          description: A secure key to encrypt your Tesla API tokens
          validRegex: /.{1,}/
        - id: $$cap_POSTGRES_VERSION
          label: Database | Version
          description: Check out their Docker page for the valid tags https://hub.docker.com/_/postgres/tags
          defaultValue: '15'
          validRegex: /.{1,}/
        - id: $$cap_DATABASE_NAME
          label: Database | Name
          defaultValue: teslamate
          description: Name of the PostgreSQL database.
          validRegex: /.{1,}/
        - id: $$cap_DATABASE_USER
          label: Database | User
          defaultValue: teslamate
          description: Username for the PostgreSQL database.
          validRegex: /.{1,}/
        - id: $$cap_DATABASE_PASS
          label: Database | Password
          description: Password of the PostgreSQL database user.
          defaultValue: $$cap_gen_random_hex(16)
          validRegex: /.{1,}/
